Bit68Task/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommapp.urls'),name=''),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommapp/urls.py
from django.contrib import admin
from django.urls import path
from ecommapp.views import *
app_name="ecommapp"
urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('allCategories/',Categories_View.as_view(),name="Categories"),
    path('productdetails/<slug:slug>/',ProductDetails_View.as_view(),name="productdetail"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("register/",CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-product/list/", AdminProductListView.as_view(), name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),name="adminproductcreate"),
    path("search/", SearchView.as_view(), name="search"),
    


    

    path('about/',About.as_view(),name="about")
]

ecommapp/models.py
from email.mime import image
from enum import unique
from pickle import TRUE
from pyexpat import model
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name



class Category(models.Model):
    title=models.CharField(max_length=200)
    slug= models.SlugField(unique=TRUE)


    def __str__(self) -> str:
        return self.title



class Product(models.Model):
    title=models.CharField(max_length=200)
    slug= models.SlugField(unique=TRUE)
    image=models.ImageField(upload_to='Products')
    Product_Price=models.PositiveIntegerField()
    description=models.TextField( )
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    view_count = models.PositiveIntegerField(default=0)




    def __str__(self) -> str:
        return self.title

class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
 

    def __str__(self):
        return "Order: " + str(self.id)

templates/Addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

templates/ProductDetails.html
tail.html
1.32 KiB
{% extends 'base.html' %}
{% block title %}{{product.title}}{% endblock %}
{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{product.title}} (Viewed {{product.view_count}} times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h4> {{product.Product_Price}}$</h4>
            {% comment %} <a href="" class="btn btn-info">Add To Cart</a> {% endcomment %}
            <a href="{% url 'ecommapp:addtocart' product.id %}" class="btn btn-info">Add To Cart</a> 
            <p>{{product.description}}</p>
        </div>
    </div>
</div> 
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% block content %}
HIdddddddddddd
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'ecommapp:home' %}">Our Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecommapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecommapp:Categories' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecommapp:mycart' %}">Cart</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'ecommapp:customerprofile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'ecommapp:customerlogout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'ecommapp:customerregistration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'ecommapp:customerlogin' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecommapp:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>
    <hr>

   
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

templates/categories.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h3>All Products</h3><hr>
    {% for cat in Category_List %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3">
            <div class="m-4">
                <h4><a href="{% url 'ecommapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
                <p class="mt-3">{{p.Product_Price}}$</p>
                <a href="{% url 'ecommapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>



{% endblock content %}

templates/checkout.html
c8648cfc
checkout.html
1.52 KiB
{% extends 'base.html' %}
{% block title %}Checkout {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'ecommapp:mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/customerlogin.html
ogin.html
928 bytes
{% extends 'base.html' %}
{% block title %}Customer Login{% endblock %}
{% block content %}
<style></style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Customer</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            {% comment %} <p> or dont have account? <a href="{% url 'ecommapp:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p> {% endcomment %}
        </div>
    </div>
</div>
{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}

{% block title %}My Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecommapp:customerorderdetail' ord.pk %}"> #ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Customer Registration{% endblock %}

{% block content %}
<style></style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register as a Customer</button>
            </form>
            {% comment %} <p> Already have an account? <a href="{% url 'ecommapp:customerlogin' %}">Login here</a></p> {% endcomment %}
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

    
    
    {% block content %}
    <div class="container">

        <h1 class="text-center">Welcome to our ecommerce website. </h1>
        <hr>
        <div class="row mt-3">
            {% for p in Product_List %}
            <div class="col-md-3 card">
                <div class="m-4">
                    <h4><a href="{% url 'ecommapp:productdetail'  p.slug%}">{{p.title}}</a></h4>
                    <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                    <h3>{{p.title}}</h3>
                    <p class="mt-3"> {{p.Product_Price}}$</p>
                   

                    <a href="{% url 'ecommapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a> 
                </div>
            </div>
            {% endfor %}
    
   
    {% endblock content %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %} My cart{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            
                             <a href="{% url 'ecommapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a> 
                            <a href="{% url 'ecommapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecommapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="">Empty Cart</a></th>
                        {% comment %} <th><a href="{% url 'ecommapp:emptycart' %}">Empty Cart</a></th> {% endcomment %}

                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        
                        <th><a class="btn btn-info" href="{% url 'ecommapp:checkout' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-3">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-9">
                    <h4><a href="{% url 'ecomapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
                    <p>Return Policy: {{result.return_policy}}</p>
                    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}